title: Testing
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: '123'
color:
  saturation: 1
  brandStrength: 0.63461161009036
  lightness: 1
  brandColors:
    - '#020308'
    - '#ffffff'
    - '#babc95'
    - '#7d8172'
    - '#0091ae'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
name: Ben. L. Photography
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
layout_spectrum: 1
